// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using contactList_BE.Data;

#nullable disable

namespace contactList_BE.Migrations
{
    [DbContext(typeof(DbCon))]
    [Migration("20240810230852_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("contactList_BE.Data.Tables.Category", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "służbowy"
                        },
                        new
                        {
                            ID = 2,
                            Name = "prywatny"
                        },
                        new
                        {
                            ID = 3,
                            Name = "inny"
                        });
                });

            modelBuilder.Entity("contactList_BE.Data.Tables.Contact", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SubCategoryID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("CategoryID");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("SubCategoryID");

                    b.ToTable("Contact");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            BirthDate = new DateTime(1973, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CategoryID = 1,
                            Email = "jakubjastak@gmail.com",
                            LastName = "Jastak",
                            Name = "Jakub",
                            Password = "BVzA;,3<W85D",
                            PhoneNumber = "826171248",
                            SubCategoryID = 1
                        },
                        new
                        {
                            ID = 2,
                            BirthDate = new DateTime(1985, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CategoryID = 2,
                            Email = "damianmendak@gmail.com",
                            LastName = "Mendak",
                            Name = "Damian",
                            Password = "0Be9##7[ueEa",
                            PhoneNumber = "350 736 024"
                        },
                        new
                        {
                            ID = 3,
                            BirthDate = new DateTime(1995, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CategoryID = 1,
                            Email = "aureliasochocka@gmail.com",
                            LastName = "Sochocka",
                            Name = "Aurelia",
                            Password = "F?cU~79:.l1u",
                            PhoneNumber = "+48930384181",
                            SubCategoryID = 2
                        },
                        new
                        {
                            ID = 4,
                            BirthDate = new DateTime(2007, 7, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CategoryID = 2,
                            Email = "lukaszfiliks@gmail.com",
                            LastName = "Filiks",
                            Name = "Łukasz",
                            Password = "1[%H7i26j2bc",
                            PhoneNumber = "522-023-813"
                        },
                        new
                        {
                            ID = 5,
                            BirthDate = new DateTime(1946, 10, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CategoryID = 2,
                            Email = "agnieszkamalarczyk@gmail.com",
                            LastName = "Malarczyk",
                            Name = "Agnieszka",
                            Password = "Hn_)6Pxe3=nK",
                            PhoneNumber = "340423962"
                        },
                        new
                        {
                            ID = 6,
                            BirthDate = new DateTime(1959, 7, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CategoryID = 3,
                            Email = "sabinaprus@gmail.com",
                            LastName = "Prus",
                            Name = "Sabina",
                            Password = "k~/V<kg}0l/y",
                            PhoneNumber = "329361319",
                            SubCategoryID = 3
                        },
                        new
                        {
                            ID = 7,
                            BirthDate = new DateTime(1981, 7, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CategoryID = 1,
                            Email = "mieczyslawwojtaszczyk@gmail.com",
                            LastName = "Wojtaszczyk",
                            Name = "Mieczysław",
                            Password = "/ixj{+xYFe7A",
                            PhoneNumber = "276108577",
                            SubCategoryID = 1
                        },
                        new
                        {
                            ID = 8,
                            BirthDate = new DateTime(1987, 9, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CategoryID = 2,
                            Email = "lenahalas@gmail.com",
                            LastName = "Hałas",
                            Name = "Lena",
                            Password = ")%{1nEBiC+jq",
                            PhoneNumber = "895743201"
                        },
                        new
                        {
                            ID = 9,
                            BirthDate = new DateTime(1988, 10, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CategoryID = 3,
                            Email = "benedyktprzybylski@gmail.com",
                            LastName = "Przybylski",
                            Name = "Benedykt",
                            Password = "KQN1_qn]Gm)/",
                            PhoneNumber = "532330198",
                            SubCategoryID = 3
                        },
                        new
                        {
                            ID = 10,
                            BirthDate = new DateTime(1962, 7, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CategoryID = 1,
                            Email = "marcelinacwynar@gmail.com",
                            LastName = "Cwynar",
                            Name = "Marcelina",
                            Password = "44%BJIqBYPck",
                            PhoneNumber = "461018986",
                            SubCategoryID = 2
                        });
                });

            modelBuilder.Entity("contactList_BE.Data.Tables.SubCategory", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("CategoryID");

                    b.ToTable("SubCategory");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CategoryID = 1,
                            Name = "szef"
                        },
                        new
                        {
                            ID = 2,
                            CategoryID = 1,
                            Name = "klient"
                        },
                        new
                        {
                            ID = 3,
                            CategoryID = 3,
                            Name = "kolega"
                        });
                });

            modelBuilder.Entity("contactList_BE.Data.Tables.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Password = "$2a$11$xYAtrJMPv.5K/Ij5/LGOaOLvCKuqd2bxGXAtzXwXOtDR90q/YB.lu",
                            UserName = "admin"
                        });
                });

            modelBuilder.Entity("contactList_BE.Data.Tables.Contact", b =>
                {
                    b.HasOne("contactList_BE.Data.Tables.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("contactList_BE.Data.Tables.SubCategory", "SubCategory")
                        .WithMany()
                        .HasForeignKey("SubCategoryID");

                    b.Navigation("Category");

                    b.Navigation("SubCategory");
                });

            modelBuilder.Entity("contactList_BE.Data.Tables.SubCategory", b =>
                {
                    b.HasOne("contactList_BE.Data.Tables.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
